language: python
python:
- "3.8"
- "nightly"
install:
- "pip install pytest"
- "pip install -r requirements.txt"
- "pip install requests"
- "pip install responses"
script: python -m pytest 
